local o = vim.o
local bo = vim.bo
local wo = vim.wo

o.termguicolors = true -- enables color in terminal
o.syntax = 'on' -- syntax highlighting?
o.errorbells = false -- bell sound on error
o.smartcase = true -- case sensitivity stuff for searching
o.showmode = false -- show current mode on last line
bo.swapfile = false -- use swapfile for buffer
o.backup = false -- backup file after overwriting a file
o.undodir = vim.fn.stdpath('config') .. '/undodir' -- dir for undofiles
o.undofile = true -- ^^
o.incsearch = true -- search highlighting fast updates
o.hidden = true
o.completeopt = 'menuone,noinsert,noselect' -- autocomplete
bo.autoindent = true -- automatically indents
bo.smartindent = true -- ^^
o.tabstop = 2
o.softtabstop = 2
o.shiftwidth = 2
o.expandtab = true
wo.number = true -- show number
wo.relativenumber = true
wo.signcolumn = 'yes'
wo.wrap = false
